### PR TITLE
Allow language-c 0.5

### PR DESCRIPTION
**Pull request by felixonmars**
Builds and works fine here.

### CODE REVIEW

**Comment by ian-ross** [comment]
@RyanGlScott @deech Do you want this constraint to be `>= 0.5 && < 0.6` to guarantee picking up the new language-c?  I can make a new 0.28.1 version of C2HS with the new constraint.

**Comment by felixonmars** [comment]
Ping? Would like to know if I should make the change.

**Comment by deech** [comment]
Yes, please go ahead. It's been a busy weekend and I couldn't get to testing on Friday.

**Comment by deech** [comment]
I see your commit uses the constraints `language-c >= 0.4.7 && < 0.6`. Is there any reason not to do `language-c >= 0.5 && < 0.6`?

**Comment by felixonmars** [comment]
Updated :)

**Comment by deech** [comment]
Confirming that C2HS correctly preprocesses files on Windows with this fix.

**Pull request merged**
