### PR TITLE
Attempting to fix build errors on Travis CI

### PR DESCRIPTION
**Pull request by kolmodin**
Upgrading GHC version, alex, happy, cabal-install.
Adding build status image to the README.

### CODE REVIEW

**Comment by kolmodin** [comment]
Looks like the travis build now works. 

I've accidentally changed a previous commit though... need to fix.

**Comment by kolmodin** [comment]
Fixed the issue.

If travis is green, this PR is ready to be merged.

**Comment by kolmodin** [comment]
I also recommend that we turn on daily or weekly builds of travis. This should allow us to learn about build breakages quicker - not only when somebody triggers the system with a new PR.

Daily/weekly builds is a setting you can turn on in travis settings for the project.

https://travis-ci.org/haskell/c2hs/settings

**Comment by kolmodin** [comment]
@ian-ross Who is the maintainer nowadays? Did you find a successor? I'd like to merge this PR and #181.

**Comment by ian-ross** [comment]
@kolmodin I passed the maintainership on to @deech some time ago.  But it looks like he's not even been added to the GitHub `haskell/c2hs` team yet...

**Comment by kolmodin** [comment]
Great! When you add him, you may consider adding me too. Or maybe I should take that up with @deech. I could merge minor things like the two PRs.

**Comment by deech** [comment]
Sorry, my fault. I think @ian-ross had asked to have my name added quite a while ago and I was supposed to bug @dcoutts about it but forgot. As it stands I'm still not a team member but I'll email him today (or maybe he'll see this :) ).

**Comment by kolmodin** [comment]
https://github.com/orgs/haskell/teams/c2hs Click on the button to ask for becoming a member.
I did that, and somebody approved the request (don't know who :)).

**Comment by deech** [comment]
Doesn't work for me. I don't even have that button which is why I need to hail @dcoutts so I can be added to the organization in the first place.

**Comment by kolmodin** [comment]
@deech, I see. @hvr is usually responsive on Github. Herbert, could you add @deech to the Haskell community and the c2hs group? He's the new maintainer for c2hs :) Thanks!

**Comment by ian-ross** [comment]
@kolmodin That works because you're already part of the GH haskell organization.

@deech Anyone on the Owners list should be able to add you (https://github.com/orgs/haskell/people?utf8=%E2%9C%93&query=%20role%3Aowner -- Duncan isn't listed there any more, so maybe try one of those people instead.)

**Comment by ian-ross** [comment]
Oops.  Crossed comments.

**Comment by kolmodin** [comment]
@dcoutts ping :)

**Comment by kolmodin** [comment]
@deech I asked around on IRC in #hackage for you about becoming a team member in haskell/c2hs so you actually can do some maintenance.
If you don't mind, since I got access myself to c2hs, I can start by merging at least my own PRs. SG?

**Comment by deech** [comment]
Yeah sure go ahead. I haven't run your changes but it seems pretty innocuous. Sorry about all this and thanks for taking the time to ask around.

**Pull request merged**
