### PR TITLE
Add InterruptibleFFI support

### PR DESCRIPTION
**Pull request by centromere**
This patch adds [InterruptibleFFI](https://downloads.haskell.org/~ghc/master/users-guide/ffi-chap.html#interruptible-foreign-calls) support.

### CODE REVIEW

**Comment by rwbarton** [comment]
I'm not sure whether c2hs needs to care about this, but the combination of `interruptible` with `unsafe` doesn't make sense. In fact GHC rejects combining `interruptible` with either `safe` or `unsafe` with a parse error; `unsafe`/`safe`/`interruptible` is a three-way choice, defaulting to `safe`.

**Comment by rwbarton** [comment]
Ah, I didn't look at everything carefully, just the parser and data structure changes. For clarity it might be better to replace the `Bool` "is unsafe?" field with a copy of GHC's `data Safety = PlaySafe | PlayInterruptible | PlayRisky` type. (But I'm not the c2hs maintainer.)

**Comment by centromere** [comment]
Any chance this could be merged in?

**Comment by deech** [comment]
This PR was added before I took over maintainership and I haven't had a chance to look over it yet. I'm traveling but will try to get to it the first week of January.

**Comment by gbaz** [comment]
pinging on this -- could really use it.

**Comment by deech** [comment]
This is now merged. Thanks for your patience.

**Pull request merged**
