### PR TITLE
Add MonadFail instance so it compiles with GHC 8.6.1

### PR DESCRIPTION
**Pull request by vmchale**
There's probably a better solution than this, but this will at least get it compiling with GHC 8.6.1

### CODE REVIEW

**Comment by gwils** [comment]
In my capacity as a hackage trustee, I've revised some versions of c2hs which were giving bad install plans with ghc 8.6

Please merge this PR or similar and release a new version soon.

**Comment by deech** [comment]
I'll cut a release sometime tomorrow.

**Comment by gwils** [comment]
Thanks :)

**Comment by deech** [comment]
It's up now. Please let me know if there are any issues. http://hackage.haskell.org/package/c2hs-0.28.6

**Pull request merged**
