### PR TITLE
Allow shelly-1.10; Haskell CI for GHC 7.10 - 9.2

### PR DESCRIPTION
**Pull request by andreasabel**
Beyond allowing `shelly-1.10`, which is completely unproblematic, the purpose of this PR is to contribute continuous integration (on Linux) that is auto-generated by `haskell-ci github`.
This required some changes to the test-suites:

1. To function in a multi-GHC environment, the `ghc` executable is now located via the `ghc-paths` package.
2. To work with `cabal v2-test`, the `c2hs` executable is put in the `PATH` by `build-tools: c2hs`.

Some cosmetic changes included in this PR:
1. Fix whitespace violations and remove tabs.
2. Comply with `-Wcompat` (for GHC >= 8).
3. Silence some import warnings.

There are some loose ends.  I commented out:
1. Parts of the testcase #102 because it was broken on my machine (macOS Mojave).
2. Testcases #128 and #257: They fail mysteriously on Haskell-CI.

After all these changes, CI runs successfully: https://github.com/andreasabel/c2hs/actions/runs/1799681516

Having to comment out some tests is of course a fly in the ointment, however, having a running multi-GHC CI outweighs this drawback.  In the future, reactivation of these test cases could be researched, but I am out of steam after already spending many hours.

ATTN: @deech

### CODE REVIEW

**Comment by deech** [comment]
This is great, thank you! I'll merge this but could you link to the CI test failures you're getting with issue 128 and 257 and maybe post the failure output for issue 102 if you still have access to it?

**Comment by andreasabel** [comment]
Excellent, @deech!  Here the details about the test failures:

The test #102 failed for me with error
```
stderr: Issue102: FCntlLockState.toEnum: Cannot match 0
```
I commented on this in the code changed in commit https://github.com/haskell/c2hs/commit/3a05b16e243fc21e056752f6327c4af94f8210be.

The CI failures for the tests #128 and #257 are documented in the commit message of https://github.com/haskell/c2hs/commit/820ac63835674ba430bce1b34ad8721fd1141d82, this is the text:

- [andreasabel/c2hs/runs/5077959414?check_suite_focus=true#step:20:435](https://github.com/andreasabel/c2hs/runs/5077959414?check_suite_focus=true#step:20:435)
```
Uncaught fatal error: ghc: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
  Issue https://github.com/haskell/c2hs/issues/128: [Failed]
ERROR:
Ran commands:
cd /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128.hs
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128.chs.h
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128.chs.c
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128.chi
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/issue128_c.o
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128.chs.o
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-128/Issue128
c2hs Issue128.chs
which c2hs
cd /__w/c2hs/c2hs/unpacked/c2hs-0.28.8

Exception: error running: c2hs Issue128.chs
exit status: 1
stderr: c2hs: does not exist (file: `

```

- [andreasabel/c2hs/runs/5077959414?check_suite_focus=true#step:20:496](https://github.com/andreasabel/c2hs/runs/5077959414?check_suite_focus=true#step:20:496)
```
Uncaught fatal error: ghc: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
  Issue https://github.com/haskell/c2hs/issues/257: [Failed]
ERROR:
Ran commands:
cd /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257.hs
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257.chs.h
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257.chs.c
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257.chi
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/issue257_c.o
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257.chs.o
rm -f /__w/c2hs/c2hs/unpacked/c2hs-0.28.8/tests/bugs/issue-257/Issue257
c2hs Issue257.chs
which c2hs
cd /__w/c2hs/c2hs/unpacked/c2hs-0.28.8

Exception: error running: c2hs Issue257.chs
exit status: 1
stderr: c2hs: does not exist (file: `

```

**Comment by andreasabel** [comment]
Btw, I relaxed the `shelly` bound in a revision: https://hackage.haskell.org/package/c2hs-0.28.8/revisions/

**Comment by deech** [comment]
Yes I should have seen that. Thanks for reposting.

**Comment by andreasabel** [comment]
I agree that it is more visible in a PR comment than in a patch description.

**Pull request merged**
